title: "Social Media Ranking Algorithm Research"
description: "Experimental research on ranking algorithms that prioritize social benefits over engagement metrics"

# GitHub Pages settings
plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings

# Markdown settings
markdown: kramdown
highlighter: rouge

# Include and exclude settings
include:
  - README.md
